apiVersion: apps/v1
kind: Deployment
metadata:
  name: hfind-deployment
spec:
  selector:
    matchLabels:
      app: hfind
  template:
    metadata:
      labels:
        app: hfind
    spec:
      containers:
        - name: hfind
          image: vasillis2000/hfind:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoDbSettings__Host
              value: mongodb-service
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hfind-service
spec:
  type: LoadBalancer
  selector:
    app: hfind
  ports:
    - port: 80
      targetPort: 80
